import { ModalCandidato } from "./ModalClass.js";
import { Candidato } from "./CandidatoClass.js";
const submitButtonCandidato = document.getElementById("submit");
const competenciasButtons = document.getElementsByClassName("competencia-btn");
const modalCandidato = document.getElementById("modalCandidato");
const closeCandidatoButton = document.getElementById("btnCloseCandidato");
const btnOpenModalCandidato = document.getElementById("cadastrarCandidato");
const nome = document.getElementById('nome');
const email = document.getElementById('email');
const cep = document.getElementById('cep');
const cidade = document.getElementById('cidade');
const estadoFederativo = document.getElementById('estadoFederativo');
const formacao = document.getElementById('formacao');
const modal = new ModalCandidato(btnOpenModalCandidato, modalCandidato, closeCandidatoButton, competenciasButtons);
const candidato = new Candidato(nome, email, cep, cidade, estadoFederativo, formacao, competenciasButtons);
submitButtonCandidato === null || submitButtonCandidato === void 0 ? void 0 : submitButtonCandidato.addEventListener('click', (e) => {
    e.preventDefault();
    const uniqueKey = `candidatoData_${new Date().getTime()}`;
    const data = candidato.collectCandidatoData();
    localStorage.setItem(uniqueKey, JSON.stringify(data));
    alert("dados salvos com sucesso");
    modal.clearCompetenciasStyle();
});
